apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params:
    - name: apikey
  tasks:
    - name: task1
      taskRef:
        name: task1
      params:
        - name: apikey
          value: $(params.apikey)
